import { Company, Vacancy } from "@/entities/vacancy/types/types";
import { Candidate } from "../types/types";

const companies: Company[] = [
  {
    id: "comp1",
    name: "TechTrend Innovations",
    icon_url: "/icons/techtrend.png",
    industry: "Software Development",
    site_url: "https://techtrend.com",
  },
  {
    id: "comp2",
    name: "DataWave Solutions",
    icon_url: "/icons/datawave.png",
    industry: "Data Analytics",
    site_url: "https://datawave.com",
  },
  {
    id: "comp3",
    name: "CreativeHR Corp",
    icon_url: "/icons/creativehr.png",
    industry: "Human Resources",
    site_url: "https://creativehr.com",
  },
  {
    id: "comp4",
    name: "CloudPeak Technologies",
    icon_url: "/icons/cloudpeak.png",
    industry: "Cloud Computing",
    site_url: "https://cloudpeak.com",
  },
];

const vacancies: Vacancy[] = [
  {
    id: 1,
    company: companies[0],
    post: "Frontend Developer",
    salary: "$80,000 - $120,000",
    tags: ["React", "TypeScript", "UI/UX"],
    isFavorite: true,
    region: "Москва",
    responsibilities: {
      title: "Key Responsibilities",
      description: [
        "Develop and maintain web applications using React and TypeScript.",
        "Collaborate with designers to implement UI/UX designs.",
        "Optimize application performance and ensure responsiveness.",
      ],
    },
    requirements: {
      title: "Requirements",
      description: [
        "3+ years of experience with React and TypeScript.",
        "Strong understanding of JavaScript and CSS.",
        "Experience with RESTful APIs.",
      ],
    },
  },
  {
    id: 2,
    company: companies[1],
    post: "Data Scientist",
    salary: "$90,000 - $140,000",
    tags: ["Python", "Machine Learning", "Data Analysis"],
    isFavorite: false,
    region: "Москва",

    responsibilities: {
      title: "Key Responsibilities",
      description: [
        "Build and deploy machine learning models.",
        "Analyze large datasets to extract insights.",
        "Collaborate with data engineers to optimize data pipelines.",
      ],
    },
    requirements: {
      title: "Requirements",
      description: [
        "Master’s degree in Data Science or related field.",
        "Proficiency in Python and SQL.",
        "Experience with TensorFlow or PyTorch.",
      ],
    },
  },
  {
    id: 3,
    company: companies[2],
    post: "HR Manager",
    salary: "$70,000 - $100,000",
    tags: ["Recruitment", "Employee Relations", "HR Strategy"],
    isFavorite: false,
    region: "Москва",

    responsibilities: {
      title: "Key Responsibilities",
      description: [
        "Manage recruitment and onboarding processes.",
        "Develop HR policies and programs.",
        "Handle employee relations and conflict resolution.",
      ],
    },
    requirements: {
      title: "Requirements",
      description: [
        "5+ years of HR experience.",
        "Strong communication and leadership skills.",
        "Knowledge of labor laws and regulations.",
      ],
    },
  },
  {
    id: 4,
    company: companies[0],
    post: "Backend Developer",
    salary: "$85,000 - $130,000",
    tags: ["Python", "Alchemist", "PostgreSQL"],
    isFavorite: true,
    region: "Москва",

    responsibilities: {
      title: "Key Responsibilities",
      description: [
        "Develop and maintain server-side applications.",
        "Design and implement RESTful APIs.",
        "Ensure application scalability and security.",
      ],
    },
    requirements: {
      title: "Requirements",
      description: [
        "4+ years of experience with Node.js and Express.",
        "Experience with MongoDB or similar databases.",
        "Understanding of microservices architecture.",
      ],
    },
  },
  {
    id: 5,
    company: companies[3],
    post: "Cloud Architect",
    salary: "$100,000 - $160,000",
    tags: ["AWS", "Azure", "Cloud Infrastructure"],
    isFavorite: false,
    responsibilities: {
      title: "Key Responsibilities",
      description: [
        "Design and implement cloud-based solutions.",
        "Optimize cloud infrastructure for performance and cost.",
        "Collaborate with DevOps teams for deployments.",
      ],
    },
    region: "Москва",
    requirements: {
      title: "Requirements",
      description: [
        "5+ years of experience in cloud architecture.",
        "Expertise in AWS and/or Azure.",
        "Strong problem-solving skills.",
      ],
    },
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: 1,
    name: "John Doe",
    vacancy: vacancies[0],
    status: "Прошли",
    match: 85,
    date: "2023-09-01",
    strengths: "Strong React skills, excellent UI/UX implementation.",
    gaps: "Limited experience with GraphQL.",
    transcript:
      "Candidate demonstrated proficiency in React and TypeScript during the interview.",
    recommendation: "На следующий этап",
    technicalScore: 90,
    communicationScore: 80,
    casesScore: 85,
  },
  {
    id: 2,
    name: "Jane Smith",
    vacancy: vacancies[1],
    status: "В обработке",
    match: 60,
    date: "2023-09-02",
    strengths: "Solid Python skills, good understanding of ML concepts.",
    gaps: "Needs more experience with production ML deployments.",
    transcript:
      "Candidate discussed their experience with Python and data analysis.",
    recommendation: "Дополнительное тестирование",
    technicalScore: 70,
    communicationScore: 65,
    casesScore: 60,
  },
  {
    id: 3,
    name: "Alice Johnson",
    vacancy: vacancies[2],
    status: "Отказ",
    match: 45,
    date: "2023-09-03",
    strengths: "Good communication skills.",
    gaps: "Lacks experience in strategic HR planning.",
    transcript: "Candidate struggled with questions on HR strategy.",
    recommendation: "Отказ",
    technicalScore: 50,
    communicationScore: 70,
    casesScore: 45,
  },
  {
    id: 4,
    name: "Мариф Магомедов",
    vacancy: vacancies[3],
    status: "Прошли",
    match: 78,
    date: "2023-09-04",
    strengths: "Proficient in Node.js and API development.",
    gaps: "Limited knowledge of containerization.",
    transcript: "Candidate showcased strong backend development skills.",
    recommendation: "На следующий этап",
    technicalScore: 85,
    communicationScore: 75,
    casesScore: 80,
  },
  {
    id: 5,
    name: "Emily Davis",
    vacancy: vacancies[4],
    status: "В обработке",
    match: 72,
    date: "2023-09-05",
    strengths: "Deep knowledge of AWS architecture.",
    gaps: "Needs more experience with Azure.",
    transcript: "Candidate discussed cloud infrastructure design.",
    recommendation: "Дополнительное тестирование",
    technicalScore: 80,
    communicationScore: 70,
    casesScore: 65,
  },
  {
    id: 6,
    name: "David Wilson",
    vacancy: vacancies[4],
    status: "Отказ",
    match: 55,
    date: "2023-09-06",
    strengths: "Familiar with cloud concepts.",
    gaps: "Lacks hands-on experience with AWS deployments.",
    transcript: "Candidate struggled with technical questions on AWS.",
    recommendation: "Отказ",
    technicalScore: 60,
    communicationScore: 65,
    casesScore: 50,
  },
  {
    id: 7,
    name: "Sarah Taylor",
    vacancy: vacancies[0],
    status: "Прошли",
    match: 90,
    date: "2023-09-07",
    strengths: "Exceptional UI/UX design skills.",
    gaps: "Limited experience with backend integration.",
    transcript: "Candidate excelled in React and UI/UX tasks.",
    recommendation: "На следующий этап",
    technicalScore: 95,
    communicationScore: 85,
    casesScore: 90,
  },
  {
    id: 8,
    name: "James Lee",
    vacancy: vacancies[3],
    status: "В обработке",
    match: 65,
    date: "2023-09-08",
    strengths: "Good understanding of Node.js.",
    gaps: "Needs improvement in database optimization.",
    transcript: "Candidate discussed backend development experience.",
    recommendation: "Дополнительное тестирование",
    technicalScore: 70,
    communicationScore: 60,
    casesScore: 65,
  },
  {
    id: 9,
    name: "Laura Martinez",
    vacancy: vacancies[1],
    status: "Отказ",
    match: 40,
    date: "2023-09-09",
    strengths: "Basic knowledge of data analysis.",
    gaps: "Lacks advanced ML skills.",
    transcript: "Candidate struggled with ML-related questions.",
    recommendation: "Отказ",
    technicalScore: 45,
    communicationScore: 55,
    casesScore: 40,
  },
  {
    id: 10,
    name: "Robert Garcia",
    vacancy: vacancies[0],
    status: "Прошли",
    match: 82,
    date: "2023-09-10",
    strengths: "Strong TypeScript and React skills.",
    gaps: "Limited experience with testing frameworks.",
    transcript: "Candidate performed well in coding tasks.",
    recommendation: "На следующий этап",
    technicalScore: 85,
    communicationScore: 80,
    casesScore: 80,
  },
  {
    id: 11,
    name: "Olivia Clark",
    vacancy: vacancies[4],
    status: "В обработке",
    match: 70,
    date: "2023-09-11",
    strengths: "Good knowledge of cloud infrastructure.",
    gaps: "Needs more experience with cost optimization.",
    transcript: "Candidate discussed AWS and Azure experience.",
    recommendation: "Дополнительное тестирование",
    technicalScore: 75,
    communicationScore: 70,
    casesScore: 70,
  },
  {
    id: 12,
    name: "William Rodriguez",
    vacancy: vacancies[1],
    status: "Отказ",
    match: 50,
    date: "2023-09-12",
    strengths: "Familiar with Python.",
    gaps: "Lacks experience with ML frameworks.",
    transcript: "Candidate struggled with ML model questions.",
    recommendation: "Отказ",
    technicalScore: 50,
    communicationScore: 60,
    casesScore: 45,
  },
  {
    id: 13,
    name: "Sophia Walker",
    vacancy: vacancies[0],
    status: "Прошли",
    match: 88,
    date: "2023-09-13",
    strengths: "Excellent React and TypeScript skills.",
    gaps: "Limited experience with CI/CD pipelines.",
    transcript: "Candidate excelled in frontend tasks.",
    recommendation: "На следующий этап",
    technicalScore: 90,
    communicationScore: 85,
    casesScore: 85,
  },
  {
    id: 14,
    name: "Daniel Hall",
    vacancy: vacancies[4],
    status: "В обработке",
    match: 75,
    date: "2023-09-14",
    strengths: "Strong AWS expertise.",
    gaps: "Needs more experience with hybrid cloud setups.",
    transcript: "Candidate discussed cloud architecture experience.",
    recommendation: "Дополнительное тестирование",
    technicalScore: 80,
    communicationScore: 75,
    casesScore: 70,
  },
  {
    id: 15,
    name: "Emma Young",
    vacancy: vacancies[2],
    status: "Отказ",
    match: 48,
    date: "2023-09-15",
    strengths: "Good interpersonal skills.",
    gaps: "Lacks strategic HR experience.",
    transcript: "Candidate struggled with HR strategy questions.",
    recommendation: "Отказ",
    technicalScore: 50,
    communicationScore: 70,
    casesScore: 45,
  },
];
